# Generated by Django 4.2.11 on 2024-05-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuthorHistories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('article_heading', models.TextField()),
                ('article_summary', models.TextField()),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('article_status', models.CharField(max_length=45)),
                ('notification_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'article_author_histories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthorSummaries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('article_status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_author_summaries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleBias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField()),
                ('left_bias', models.CharField(blank=True, max_length=255, null=True)),
                ('right_bias', models.CharField(blank=True, max_length=255, null=True)),
                ('center_bias', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_bias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleBiasedSentences',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField(blank=True, null=True)),
                ('biased_sentence', models.TextField(blank=True, null=True)),
                ('biased_type', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_biased_sentences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleBreakingNews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField()),
                ('breaking_news_period', models.IntegerField()),
                ('article_visited', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_breaking_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleDeleteProofs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('article_heading', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'article_delete_proofs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleHashtags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_category', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('left_color', models.CharField(blank=True, max_length=45, null=True)),
                ('right_color', models.CharField(blank=True, max_length=45, null=True)),
                ('is_available', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'article_hashtags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticlePolls',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField()),
                ('poll_question', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('poll_image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('left_color', models.CharField(blank=True, max_length=255, null=True)),
                ('right_color', models.CharField(blank=True, max_length=255, null=True)),
                ('poll_published', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'article_polls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticlePublishTimes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('article_publish_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'article_publish_times',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_heading', models.CharField(max_length=200)),
                ('article_summary', models.CharField(max_length=500)),
                ('article_author', models.CharField(max_length=255)),
                ('main_source', models.TextField()),
                ('additional_sources', models.TextField(blank=True, null=True)),
                ('article_image', models.TextField(blank=True, null=True)),
                ('article_category', models.CharField(max_length=255)),
                ('article_keywords', models.TextField(blank=True, null=True)),
                ('targetting_states', models.TextField(blank=True, null=True)),
                ('left_color', models.CharField(blank=True, max_length=255, null=True)),
                ('right_color', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_article', models.CharField(max_length=255)),
                ('article_status', models.CharField(max_length=255)),
                ('article_priority', models.CharField(blank=True, max_length=255, null=True)),
                ('button_class', models.CharField(blank=True, max_length=255, null=True)),
                ('priority_button_class', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('priority_class', models.CharField(blank=True, max_length=255, null=True)),
                ('time_ago', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_text', models.TextField(blank=True, null=True)),
                ('notification_sent_status', models.CharField(blank=True, max_length=45, null=True)),
                ('trending_news', models.CharField(blank=True, max_length=45, null=True)),
                ('breaking_news', models.CharField(blank=True, max_length=45, null=True)),
                ('article_bias', models.CharField(blank=True, max_length=45, null=True)),
                ('additional_source_bias', models.CharField(blank=True, max_length=45, null=True)),
                ('is_embed_link', models.CharField(blank=True, max_length=10, null=True)),
                ('read_more_text', models.CharField(blank=True, max_length=45, null=True)),
                ('read_more_text_color', models.CharField(blank=True, max_length=45, null=True)),
                ('article_subcategories', models.CharField(blank=True, max_length=45, null=True)),
                ('likes_count', models.BigIntegerField(default=0)),
                ('comments_count', models.BigIntegerField(default=0)),
                ('article_publisher', models.BigIntegerField(default=1)),
                ('article_video_url', models.TextField(blank=True, null=True)),
                ('pop_score', models.FloatField(blank=True, null=True)),
                ('article_video_validity_checked', models.CharField(blank=True, max_length=45, null=True)),
                ('auto_likes_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleSentenceBias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_heading', models.TextField(blank=True, null=True)),
                ('article_sentence', models.TextField(blank=True, null=True)),
                ('bias_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_sentence_bias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleStatuses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Articletimestamp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField(blank=True, null=True)),
                ('time_ago', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ArticleTimeStamp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=255)),
                ('category_image_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.CharField(blank=True, max_length=10, null=True)),
                ('left_color', models.CharField(blank=True, max_length=45, null=True)),
                ('right_color', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Digs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dig_title', models.CharField(max_length=255)),
                ('dig_body', models.TextField()),
                ('dig_image_path', models.CharField(max_length=255)),
                ('dig_author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'digs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('documentid', models.CharField(blank=True, db_column='documentId', max_length=255, null=True)),
                ('article_id', models.IntegerField(blank=True, null=True)),
                ('feedback_title', models.TextField()),
                ('feedback_type', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_body', models.TextField(blank=True, null=True)),
                ('options_count', models.CharField(blank=True, max_length=45, null=True)),
                ('option1', models.TextField(blank=True, null=True)),
                ('option2', models.TextField(blank=True, null=True)),
                ('option3', models.TextField(blank=True, null=True)),
                ('slider_min', models.CharField(blank=True, max_length=255, null=True)),
                ('slider_max', models.CharField(blank=True, max_length=255, null=True)),
                ('slider_stops', models.IntegerField(blank=True, null=True)),
                ('feedback_image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('left_color', models.CharField(blank=True, max_length=255, null=True)),
                ('right_color', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_published', models.CharField(blank=True, max_length=45, null=True)),
                ('has_slides', models.CharField(blank=True, max_length=45, null=True)),
                ('slides_count', models.IntegerField(blank=True, null=True)),
                ('slides', models.CharField(blank=True, max_length=255, null=True)),
                ('option4', models.CharField(blank=True, max_length=45, null=True)),
                ('option5', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('feedback_id', models.CharField(blank=True, max_length=45, null=True)),
                ('feedbackid', models.BigIntegerField(blank=True, db_column='feedbackId', null=True)),
                ('documentid', models.CharField(blank=True, db_column='documentId', max_length=255, null=True)),
                ('disabled', models.CharField(blank=True, max_length=10, null=True)),
                ('slide_id', models.CharField(blank=True, max_length=45, null=True)),
                ('user_id', models.CharField(blank=True, max_length=45, null=True)),
                ('feedback_type', models.CharField(blank=True, max_length=45, null=True)),
                ('feedback_answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('option_selected', models.TextField(blank=True, null=True)),
                ('slider_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackSlides',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feedback_title', models.TextField()),
                ('feedback_type', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_body', models.TextField(blank=True, null=True)),
                ('options_count', models.CharField(blank=True, max_length=45, null=True)),
                ('option1', models.TextField(blank=True, null=True)),
                ('option2', models.TextField(blank=True, null=True)),
                ('option3', models.TextField(blank=True, null=True)),
                ('slider_min', models.CharField(blank=True, max_length=255, null=True)),
                ('slider_max', models.CharField(blank=True, max_length=255, null=True)),
                ('slider_stops', models.IntegerField(blank=True, null=True)),
                ('feeback_image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('left_color', models.CharField(blank=True, max_length=255, null=True)),
                ('right_color', models.CharField(blank=True, max_length=255, null=True)),
                ('option4', models.CharField(blank=True, max_length=45, null=True)),
                ('option5', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'feedback_slides',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleTrendsArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=200, null=True)),
                ('article_url', models.CharField(blank=True, max_length=200, null=True)),
                ('article_source', models.CharField(blank=True, max_length=200, null=True)),
                ('article_category', models.CharField(blank=True, max_length=200, null=True)),
                ('article_pubilsh_time', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'google_trends_articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleTrendsArticlesBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=200, null=True)),
                ('article_url', models.CharField(blank=True, max_length=200, null=True)),
                ('article_source', models.CharField(blank=True, max_length=200, null=True)),
                ('article_category', models.CharField(blank=True, max_length=200, null=True)),
                ('article_pubilsh_time', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'google_trends_articles_business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleTrendsArticlesEntertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=200, null=True)),
                ('article_url', models.CharField(blank=True, max_length=200, null=True)),
                ('article_source', models.CharField(blank=True, max_length=200, null=True)),
                ('article_category', models.CharField(blank=True, max_length=200, null=True)),
                ('article_pubilsh_time', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'google_trends_articles_entertainment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleTrendsArticlesHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=200, null=True)),
                ('article_url', models.CharField(blank=True, max_length=200, null=True)),
                ('article_source', models.CharField(blank=True, max_length=200, null=True)),
                ('article_category', models.CharField(blank=True, max_length=200, null=True)),
                ('article_pubilsh_time', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'google_trends_articles_health',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleTrendsArticlesSciNTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=200, null=True)),
                ('article_url', models.CharField(blank=True, max_length=200, null=True)),
                ('article_source', models.CharField(blank=True, max_length=200, null=True)),
                ('article_category', models.CharField(blank=True, max_length=200, null=True)),
                ('article_pubilsh_time', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'google_trends_articles_sci_n_tech',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleTrendsArticlesSports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=200, null=True)),
                ('article_url', models.CharField(blank=True, max_length=200, null=True)),
                ('article_source', models.CharField(blank=True, max_length=200, null=True)),
                ('article_category', models.CharField(blank=True, max_length=200, null=True)),
                ('article_pubilsh_time', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'google_trends_articles_sports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleTrendsArticlesTopStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=200, null=True)),
                ('article_url', models.CharField(blank=True, max_length=200, null=True)),
                ('article_source', models.CharField(blank=True, max_length=200, null=True)),
                ('article_category', models.CharField(blank=True, max_length=200, null=True)),
                ('article_pubilsh_time', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'google_trends_articles_top_stories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration', models.CharField(max_length=255)),
                ('batch', models.IntegerField()),
            ],
            options={
                'db_table': 'migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationAuthorSummaries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('notification_text', models.CharField(max_length=255)),
                ('notffication_status', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent_count', models.IntegerField(blank=True, null=True)),
                ('notification_failure_count', models.CharField(blank=True, max_length=45, null=True)),
                ('invalid_count', models.CharField(blank=True, max_length=45, null=True)),
                ('not_registered_count', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'notification_author_summaries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationOpens',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_user_id', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification_opens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationStatusEachUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_heading', models.TextField()),
                ('app_username', models.CharField(max_length=255)),
                ('sent_status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('article_image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification_status_each_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTemp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'password_resets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PollResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.CharField(blank=True, max_length=45, null=True)),
                ('user_id', models.CharField(blank=True, max_length=45, null=True)),
                ('option_selected', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'poll_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publisher_title', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher_content', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.CharField(blank=True, max_length=10, null=True)),
                ('left_color', models.CharField(blank=True, max_length=45, null=True)),
                ('right_color', models.CharField(blank=True, max_length=45, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('article_publish_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'publishers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepublishableArticles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'republishable_articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RssPoliticsNews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_title', models.TextField()),
                ('article_description', models.TextField()),
                ('published_date', models.TextField()),
                ('main_source', models.TextField()),
                ('image_url', models.TextField()),
                ('source_name', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rss_politics_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RssUsNews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_title', models.TextField()),
                ('article_description', models.TextField()),
                ('published_date', models.TextField()),
                ('main_source', models.TextField()),
                ('image_url', models.TextField()),
                ('source_name', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rss_us_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RssWorldNews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_title', models.TextField()),
                ('article_description', models.TextField()),
                ('published_date', models.TextField()),
                ('main_source', models.TextField()),
                ('image_url', models.TextField()),
                ('source_name', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rss_world_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaveBreakingNewsTokens',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('fcm_token', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'save_breaking_news_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SponsoredArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sponsored_articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPaymentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'subscription_payment_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_pricing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'subscription_promo_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.IntegerField(blank=True, null=True)),
                ('is_trial', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrendingArticles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_heading', models.CharField(max_length=255)),
                ('main_source', models.CharField(max_length=255)),
                ('article_image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trending_articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrendingCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trending_title', models.CharField(max_length=255)),
                ('trending_category_image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trending_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrendingSaveArticles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_source', models.TextField(blank=True, null=True)),
                ('url_to_image', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('publishedat', models.CharField(blank=True, db_column='publishedAt', max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trending_save_articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=45, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VolvAppUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('date_of_registration', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'volv_app_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeekendArticles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_id', models.IntegerField()),
                ('publish_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weekend_articles',
                'managed': False,
            },
        ),
    ]
